id = "regex-theme"
name = "RegEx Theme"
version = "0.11.11"
schema_version = 2
authors = ["oxnan","RegEx The Cat"]
description = "A high-contrast black theme with muted gray text and restrained blue, cyan, orange, and magenta accents designed for clarity and long coding sessions."
repository = "https://github.com/oxnan/RegEx-theme"
